### ISSUE TITLE
Enhancement map

### ISSUE THREAD

**Issue by Darcy103** [SHI-Labs/SGL-Retinal-Vessel-Segmentation#2]
Thank you very much for your research work.
 I have a question to ask you. Does the enhancement map have GT supervision? Or is it just an intermediate result of the three channels learned by the first network?

**Comment by yzhouas** [comment]
Thanks for your interests. There is no GT for the enhancement map, but ony the intermediate result in the middle bottleneck layers. It can be well learned to illustrate the vessel structure because it can also learn information from the segmentation loss in the final layer.
